KIT ;
  IDL VERSION 1.2.8 ;
  TITLE 'Шесть вопросов' ;
  AUTHOR 'Спиридонова К.С.' ;
  CREATION DATE 19/11/2018 ;
  PROJECT NAME 'Курсовая' ;

  MODEL 'Шесть вопросов'
    {LWI
    F 0 -13 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 1 -24 0 0 0 400
      0 0 0 204 3 2 1 34
      190 'Arial'
    F 2 -11 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Courier New'
    F 3 -10 0 0 0 400
      0 0 1 204 3 2 1 34
      80 'Dialog'
    F 4 -8 0 0 0 400
      0 0 0 204 3 2 1 34
      60 'Dialog'
    F 5 -10 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Dialog'
    F 6 -8 0 0 0 400
      0 0 1 204 3 2 1 34
      60 'Dialog'
    D 0 0 0 0 0 1 0 0 2
    G 0 1
    T 'WORKING'
    R 77
    M 0 }
   ;
    AUTHOR 'Спиридонова К.С.' ;
    PROJECT NAME 'Курсовая' ;
    DIAGRAM GRAPHIC -0 ;
      CREATION DATE 17/9/2018 ;
      REVISION DATE 17/9/2018 ;
      TITLE 'Шесть вопросов' ;
      STATUS WORKING ;

      BOX 0 ;
        NAME '{LWI I 3 255 255 255}Информационно - советующая система' ;
        BOX COORDINATES (0,366;0,579) (0,576;0,342) ;
        DETAIL REFERENCE N 0 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER ;
        PATH (0,019;0,472)(0,366;0,472) ;
        LABEL '{LWI I 0 255 255 }Необходимый<CR>набор знаний<CR>человека' ;
        LABEL COORDINATES (0,166;0,524) ;
        SINK BOX 0I1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER ;
        PATH (0,534;0,031)(0,534;0,342) ;
        LABEL '{LWI I 0 255 255 }При поломке<CR>оборудования' ;
        LABEL COORDINATES (0,537;0,201) ;
        SINK BOX 0C1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 0O1 ;
        PATH (0,576;0,488)(0,977;0,488) ;
        LABEL '{LWI I 0 255 255 }Совет по<CR>устранению<CR>поломки' ;
        LABEL COORDINATES (0,732;0,542) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BORDER ;
        PATH (0,402;0,968)(0,402;0,579) ;
        LABEL '{LWI I 0 255 255 }Работник<CR>инженер<CR>организации' ;
        LABEL COORDINATES (0,405;0,779) ;
        SINK BOX 0M1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER ;
        PATH (0,528;0,968)(0,528;0,579) ;
        LABEL '{LWI I 0 255 255 }Рабочая<CR>станция' ;
        LABEL COORDINATES (0,542;0,792) ;
        SINK BOX 0M2 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BORDER ;
        PATH (0,439;0,031)(0,439;0,342) ;
        LABEL '{LWI I 0 255 255 }Инструкция к<CR>оборудованию' ;
        LABEL COORDINATES (0,337;0,192) ;
        SINK BOX 0C2 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC 0 ;
      CREATION DATE 17/9/2018 ;
      REVISION DATE 17/9/2018 ;
      TITLE 'Информационно - советующая система' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 3 255 255 255}Управление при поломке оборудования' ;
        BOX COORDINATES (0,108;0,315) (0,22;0,188) ;
        DETAIL REFERENCE N 1 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 3 255 255 255}Получение совета по устранению поломки (или по ее классификации)' ;
        BOX COORDINATES (0,4;0,606) (0,61;0,46) ;
        DETAIL REFERENCE N 2 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 3 255 255 255}Проверять качество совета' ;
        BOX COORDINATES (0,815;0,821) (0,903;0,707) ;
        DETAIL REFERENCE N 3 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER I1 (0,019;0,526) ;
        PATH (0,019;0,526)(0,4;0,526) ;
        LABEL '{LWI I 0 255 255 }Необходимый<CR>набор знаний<CR>человека' ;
        LABEL COORDINATES (0,02;0,642) ;
        SQUIGGLE COORDINATES (0,07;0,597) (0,07;0,526) ;
        SINK BOX 2I1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER C1 (0,163;0,031) ;
        PATH (0,163;0,031)(0,163;0,188) ;
        LABEL '{LWI I 0 255 255 }При поломке<CR>оборудования' ;
        LABEL COORDINATES (0,181;0,083) ;
        SQUIGGLE COORDINATES (0,181;0,092) (0,163;0,092) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 3O1 ;
        PATH (0,903;0,795)(0,977;0,795) ;
        LABEL '{LWI I 0 255 255 }Совет по<CR>устранению<CR>поломки' ;
        LABEL COORDINATES (0,908;0,897) ;
        SQUIGGLE COORDINATES (0,937;0,851) (0,937;0,795) ;
        SINK BORDER O1 (0,977;0,795) ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BORDER M1 (0,138;0,968) ;
        PATH (0,138;0,968)(0,138;0,905) ;
        LABEL 'Работник - инженер организации' ;
        SINK BRANCH 7 6 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER M2 (0,457;0,968) ;
        PATH (0,457;0,968)(0,457;0,818) ;
        LABEL 'Рабочая станция' ;
        SINK BRANCH 11 10 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BRANCH 4 ;
        PATH (0,138;0,905)(0,138;0,315) ;
        LABEL 'Работник - инженер организации' ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BRANCH 4 ;
        PATH (0,138;0,905)(0,547;0,905)(0,547;0,862) ;
        LABEL '{LWI I 0 255 255 }Работник<CR>инженер<CR>организации' ;
        LABEL COORDINATES (0,215;0,751) ;
        SQUIGGLE COORDINATES (0,22;0,797) (0,22;0,905) ;
        SINK BRANCH 8 9 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BRANCH 7 ;
        PATH (0,547;0,862)(0,547;0,606) ;
        LABEL 'Работник - инженер организации' ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BRANCH 7 ;
        PATH (0,547;0,862)(0,85;0,862)(0,85;0,821) ;
        LABEL 'Работник - инженер организации' ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 5 ;
        PATH (0,457;0,818)(0,457;0,606) ;
        LABEL 'Рабочая станция' ;
        SINK BOX 2M2 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 5 ;
        PATH (0,457;0,818)(0,184;0,818)(0,184;0,315) ;
        LABEL '{LWI I 0 255 255 }Рабочая<CR>станция' ;
        LABEL COORDINATES (0,381;0,692) ;
        SQUIGGLE COORDINATES (0,433;0,724) (0,433;0,818) ;
        SINK BOX 1M2 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BOX 2O1 ;
        PATH (0,61;0,554)(0,682;0,554)(0,682;0,764)(0,815;0,764) ;
        LABEL '{LWI I 0 255 255 }Набор советов по<CR>устранению<CR>поломки' ;
        LABEL COORDINATES (0,712;0,651) ;
        SQUIGGLE COORDINATES (0,712;0,697) (0,682;0,732) ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BOX 3O2 ;
        PATH (0,903;0,738)(0,927;0,738)(0,927;0,137)(0,649;0,137) ;
        LABEL '{LWI I 0 255 255 }Совет не<CR>подходит<CR>под<CR>условия' ;
        LABEL COORDINATES (0,79;0,074) ;
        SQUIGGLE COORDINATES (0,849;0,133) (0,917;0,137) ;
        SINK JOIN 14 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE JOIN 15 13 ;
        PATH (0,649;0,137)(0,039;0,137)(0,039;0,253)(0,108;0,253) ;
        LABEL '{LWI I 0 255 255 }Совет не<CR>готов' ;
        LABEL COORDINATES (0,532;0,183) ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BOX 2O2 ;
        PATH (0,61;0,506)(0,649;0,506)(0,649;0,137) ;
        LABEL '{LWI I 0 255 255 }Заданной<CR>поломки<CR>нет в базе' ;
        LABEL COORDINATES (0,561;0,388) ;
        SQUIGGLE COORDINATES (0,625;0,342) (0,649;0,342) ;
        SINK JOIN 14 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BOX 1O1 ;
        PATH (0,22;0,24)(0,483;0,24)(0,483;0,278) ;
        LABEL '{LWI I 0 255 255 }Инструкция к<CR>оборудованию' ;
        LABEL COORDINATES (0,386;0,31) ;
        SINK BRANCH 17 18 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BRANCH 16 ;
        PATH (0,483;0,278)(0,483;0,46) ;
        LABEL 'Инструкция к оборудованию' ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE BRANCH 16 ;
        PATH (0,483;0,278)(0,868;0,278)(0,868;0,707) ;
        LABEL 'Инструкция к оборудованию' ;
        SINK BOX 3C1 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC 2 ;
      CREATION DATE 17/9/2018 ;
      REVISION DATE 17/9/2018 ;
      TITLE 'Получение совета по устранению поломки (или по ее классификации)' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 5 255 255 255}Задача дать совет по устранению поломки' ;
        BOX COORDINATES (0,122;0,37) (0,23;0,206) ;
        DETAIL REFERENCE N 21 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 6 255 255 255}БД: Советы по устранению поломок' ;
        BOX COORDINATES (0,147;0,897) (0,249;0,806) ;
        DETAIL REFERENCE N 21 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 5 255 255 255}Совет должен соответствовать заданным параметрам' ;
        BOX COORDINATES (0,327;0,47) (0,449;0,324) ;
        DETAIL REFERENCE N 22 ;
      ENDBOX ;
      BOX 4 ;
        NAME '{LWI I 5 255 255 255}Общий список поломок по классификации' ;
        BOX COORDINATES (0,547;0,579) (0,659;0,442) ;
        DETAIL REFERENCE N 23 ;
      ENDBOX ;
      BOX 5 ;
        NAME '{LWI I 6 255 255 255}БД поломок оборудования организации' ;
        BOX COORDINATES (0,634;0,824) (0,722;0,733) ;
        DETAIL REFERENCE N 23 ;
      ENDBOX ;
      BOX 6 ;
        NAME '{LWI I 5 255 255 255}Конкретная поломка' ;
        BOX COORDINATES (0,795;0,679) (0,883;0,56) ;
        DETAIL REFERENCE N 24 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER I1 (0,019;0,286) ;
        PATH (0,019;0,286)(0,122;0,286) ;
        LABEL '{LWI I 0 255 255 }Необходимый<CR>набор знаний<CR>человека' ;
        LABEL COORDINATES (0,025;0,351) ;
        SQUIGGLE COORDINATES (0,081;0,306) (0,081;0,286) ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER M2 (0,178;0,968) ;
        PATH (0,178;0,968)(0,178;0,897) ;
        LABEL '{LWI I 0 255 255 }Рабочая<CR>станция' ;
        LABEL COORDINATES (0,103;0,929) ;
        SQUIGGLE COORDINATES (0,156;0,935) (0,178;0,935) ;
        SINK BRANCH 17 18 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER M1 (0,374;0,968) ;
        PATH (0,374;0,968)(0,374;0,47) ;
        LABEL '{LWI I 0 255 255 }Работник<CR>инженер<CR>организации' ;
        LABEL COORDINATES (0,386;0,76) ;
        SQUIGGLE COORDINATES (0,386;0,78) (0,374;0,78) ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BOX 2O1 ;
        PATH (0,249;0,846)(0,977;0,846) ;
        LABEL '{LWI I 0 255 255 }Набор советов<CR>по устранению<CR>поломки' ;
        LABEL COORDINATES (0,888;0,915) ;
        SQUIGGLE COORDINATES (0,892;0,87) (0,892;0,846) ;
        SINK BORDER O1 (0,977;0,846) ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BOX 5O1 ;
        PATH (0,722;0,785)(0,977;0,785) ;
        LABEL '{LWI I 0 255 255 }Заданной<CR>поломки<CR>нет в базе' ;
        LABEL COORDINATES (0,912;0,706) ;
        SQUIGGLE COORDINATES (0,912;0,751) (0,904;0,785) ;
        SINK BORDER O2 (0,977;0,785) ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE TUNNEL  {LWI Q}BORDER ;
        PATH (0,162;0,031)(0,162;0,206) ;
        LABEL '{LWI I 0 255 255 }Инструкция к<CR>оборудованию' ;
        LABEL COORDINATES (0,181;0,147) ;
        SQUIGGLE COORDINATES (0,181;0,148) (0,162;0,148) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BOX 2C1 ;
        PATH (0,162;0,806)(0,162;0,565)(0,147;0,565)(0,147;0,37) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BOX 2C2 ;
        PATH (0,187;0,806)(0,187;0,399)(0,327;0,399) ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BOX 3I2 ;
        PATH (0,327;0,43)(0,221;0,43)(0,221;0,806) ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BOX 1O1 ;
        PATH (0,23;0,266)(0,392;0,266)(0,392;0,324) ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BOX 3O1 ;
        PATH (0,449;0,399)(0,592;0,399)(0,592;0,442) ;
        SINK BOX 4C1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BOX 4O1 ;
        PATH (0,659;0,507)(0,837;0,507)(0,837;0,56) ;
        SINK BOX 6C1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BOX 5C1 ;
        PATH (0,664;0,733)(0,664;0,624)(0,613;0,624)(0,613;0,579) ;
        SINK BOX 4M1 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BOX 5C2 ;
        PATH (0,687;0,733)(0,687;0,603)(0,795;0,603) ;
        SINK BOX 6I1 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BOX 6I2 ;
        PATH (0,795;0,644)(0,705;0,644)(0,705;0,733) ;
        SINK BOX 5C3 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BOX 5C4 ;
        PATH (0,645;0,733)(0,645;0,659)(0,402;0,659)(0,402;0,47) ;
        SINK BOX 3M2 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BRANCH 2 ;
        PATH (0,178;0,931)(0,178;0,897) ;
        LABEL 'Рабочая станция' ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE BRANCH 2 ;
        PATH (0,178;0,931)(0,679;0,931)(0,679;0,824) ;
        LABEL 'Рабочая станция' ;
        SINK BOX 5M1 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC 3 ;
      CREATION DATE 17/9/2018 ;
      REVISION DATE 17/9/2018 ;
      TITLE 'Проверять качество совета' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 3 255 255 255}Проверка качества совета' ;
        BOX COORDINATES (0,127;0,315) (0,215;0,197) ;
        DETAIL REFERENCE N 31 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 6 255 255 255}БД: Советы по устранению поломок' ;
        BOX COORDINATES (0,171;0,924) (0,293;0,87) ;
        DETAIL REFERENCE N 31 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 3 255 255 255}Проверка соответствия заданных пользователем параметров' ;
        BOX COORDINATES (0,342;0,57) (0,454;0,37) ;
        DETAIL REFERENCE N 32 ;
      ENDBOX ;
      BOX 4 ;
        NAME '{LWI I 3 255 255 255}Общая классификация поломки' ;
        BOX COORDINATES (0,556;0,624) (0,698;0,488) ;
        DETAIL REFERENCE N 33 ;
      ENDBOX ;
      BOX 5 ;
        NAME '{LWI I 6 255 255 255}БД поломок оборудования организации' ;
        BOX COORDINATES (0,556;0,87) (0,673;0,788) ;
        DETAIL REFERENCE N 33 ;
      ENDBOX ;
      BOX 6 ;
        NAME '{LWI I 3 255 255 255}Конкретная поломка' ;
        BOX COORDINATES (0,805;0,77) (0,893;0,651) ;
        DETAIL REFERENCE N 34 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER M1 (0,161;0,968) ;
        PATH (0,161;0,968)(0,161;0,315) ;
        LABEL '{LWI I 0 255 255 }Работник<CR>инженер<CR>организации' ;
        LABEL COORDINATES (0,059;0,651) ;
        SQUIGGLE COORDINATES (0,137;0,607) (0,161;0,607) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER I1 (0,019;0,256) ;
        PATH (0,019;0,256)(0,127;0,256) ;
        LABEL '{LWI I 0 255 255 }Набор советов по<CR>устранению<CR>поломки' ;
        LABEL COORDINATES (0,01;0,315) ;
        SQUIGGLE COORDINATES (0,091;0,27) (0,091;0,256) ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 2O1 ;
        PATH (0,293;0,894)(0,977;0,894) ;
        LABEL '{LWI I 0 255 255 }Совет по<CR>устранению<CR>поломки' ;
        LABEL COORDINATES (0,908;0,824) ;
        SQUIGGLE COORDINATES (0,927;0,87) (0,927;0,894) ;
        SINK BORDER O1 (0,977;0,894) ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BOX 6O1 ;
        PATH (0,893;0,717)(0,977;0,717) ;
        LABEL '{LWI I 0 255 255 }Совет не<CR>подходит<CR>под<CR>условия' ;
        LABEL COORDINATES (0,917;0,62) ;
        SQUIGGLE COORDINATES (0,917;0,679) (0,906;0,717) ;
        SINK BORDER O2 (0,977;0,717) ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER C1 (0,169;0,031) ;
        PATH (0,169;0,031)(0,169;0,197) ;
        LABEL '{LWI I 0 255 255 }Инструкция к<CR>оборудованию' ;
        LABEL COORDINATES (0,186;0,101) ;
        SQUIGGLE COORDINATES (0,186;0,126) (0,169;0,126) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BOX 2C1 ;
        PATH (0,192;0,87)(0,192;0,315) ;
        SINK BOX 1M2 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BOX 2C2 ;
        PATH (0,232;0,87)(0,232;0,43)(0,342;0,43) ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BOX 3I2 ;
        PATH (0,342;0,505)(0,272;0,505)(0,272;0,87) ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BOX 1O1 ;
        PATH (0,215;0,254)(0,397;0,254)(0,397;0,37) ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BOX 3O1 ;
        PATH (0,454;0,457)(0,61;0,457)(0,61;0,488) ;
        SINK BOX 4C1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BOX 4O1 ;
        PATH (0,698;0,548)(0,843;0,548)(0,843;0,651) ;
        SINK BOX 6C1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BOX 5C1 ;
        PATH (0,578;0,788)(0,578;0,706)(0,406;0,706)(0,406;0,57) ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BOX 5C2 ;
        PATH (0,597;0,788)(0,597;0,624) ;
        SINK BOX 4M1 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BOX 5C3 ;
        PATH (0,615;0,788)(0,615;0,689)(0,805;0,689) ;
        SINK BOX 6I1 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BOX 6I2 ;
        PATH (0,805;0,731)(0,64;0,731)(0,64;0,788) ;
        SINK BOX 5C4 ;
      ENDSEG ;
    ENDDIAGRAM ;
  ENDMODEL ;
ENDKIT ;
